### ISSUE TITLE
請問一下用nodeJS該怎麼寫驗證(¯―¯٥)

### ISSUE THREAD

**Issue by XinBow99** [llzsrt/hahamut-bot-example#1]
不會寫ＱＱ

**Comment by llzsrt** [comment]
抱歉現在才看到(¯―¯٥)

驗證的話其實巴哈官方文件裡有範例
直接抄就可以了
https://sites.google.com/gamer.com.tw/hahamut-bot/%E6%8E%A5%E6%94%B6webhook%E4%BA%8B%E4%BB%B6
